Updated kernel and busybox versions in UML environment (#657)

diff --git a/tools/cluster_sim_uml/build_uml b/tools/cluster_sim_uml/build_uml
--- a/tools/cluster_sim_uml/build_uml
+++ b/tools/cluster_sim_uml/build_uml
@@ -33,12 +33,11 @@ xerces_lib=/usr/lib
 netsnmp_prefix=`net-snmp-config --prefix`
 netsnmp_lib=`net-snmp-config --libdir | sed 's/\-L//g'`
 
-opensaf_home=$PWD/../..
+opensaf_home=$(cd ../..; pwd)
 top=`pwd`
 bin=$top/bin
 archive=$top/archive
 scripts=$archive/scripts
-kver=${KVER:-2.6.24.3}
 
 die() {
     echo "ERROR: $*"
@@ -52,11 +51,30 @@ test -e $netsnmp_lib/libnetsnmp.so || \
 test -e $xerces_lib/libxerces-c.so || \
     die "Cannot find xerces libraries in: $xerces_lib"
 
+
+install_testprog() {
+    echo "Building and installing test program"
+    src=$opensaf_home/samples/avsv
+    libd=$top/rootfs/usr/local/$lib_dir
+    installd=$top/rootfs/opt/amf_demo
+    immxml=$top/rootfs/etc/opensaf/imm.xml
+
+    mkdir -p $installd
+    cp $src/amf_demo_script $installd
+    gcc -g -O2 -Wall -fPIC -I$opensaf_home/osaf/libs/saf/include \
+	-o $installd/amf_demo $src/amf_comp_template.c \
+	-L$libd -lSaAmf -L$libd/opensaf -lavsv_common -lopensaf_core
+
+    test -r $immxml.orig || cp $immxml $immxml.orig
+    $opensaf_home/tools/devel/immtools/immxml-merge \
+	$immxml.orig $src/AppConfig-2N.xml > $immxml
+    $opensaf_home/tools/devel/immtools/immxml-validate $immxml
+}
+
 create_rootfs()
 {
     local root=$top/rootfs
     local opensafconfig=$root/etc/opensaf
-    local bom_xml=$root/etc/opensaf/NCSSystemBOM.xml
 
     echo "Removing old root file system: $root"
     rm -rf $root
@@ -87,11 +105,6 @@ create_rootfs()
 
     # The var directory structure is setup from within each UML
     rm -rf var/*
-
-    echo "Patch BOM xml, reduce cluster init time"
-    cat $bom_xml | sed 's/<clusterInitTime>40000/<clusterInitTime>4000/g' > \
-        $bom_xml.tmp
-    mv $bom_xml.tmp $bom_xml
 
     # Required by e.g. the snmpd script
     cp $archive/snmp*d.conf etc/snmp
@@ -136,39 +149,28 @@ create_rootfs()
     # Change LOG configuration to use "replicated" disk
     sed -i 's/=${LOCALSTATEDIR}\/saflog/=repl_opensaf\/saflog/g' etc/opensaf/saflog.conf
 
-    echo "Building aishello"
-    export OPENSAF_INCLUDE=$root/usr/local/include
-    export OPENSAF_LIB=$root/usr/local/$lib_dir
-    $top/Hello/install.sh $root
-    install -m 644 $top/Hello/AppConfig.xml etc/opensaf
-
     # Copy local timezone settings
     test -f /etc/localtime && install /etc/localtime etc
-
-    cd - >& /dev/null
+    cd $top
 
     # Create a dummy /etc/hosts file, will be populated at start
     touch $root/etc/hosts
 
+    test -n "$INSTALL_TESTPROG" && install_testprog
     rm -rf $root/usr/local/include
 
     echo "Creating [$root/root.cpio] ..."
     $bin/mklndircpio $root $root/root.cpio /hostfs/rootfs >& /dev/null
 }
 
-find rootfs -name ncs_nid >& /dev/null
-if test $? = 0; then
+
+if find rootfs -name ncs_nid >& /dev/null; then
     echo "OpenSAF seems to be installed already, cowardly refusing..."
     echo "   Remove directory 'rootfs' if a fresh install is needed"
     exit 0
 fi
 
 # Build the Linux UML binary
-if uml/build_uml; then
-    create_rootfs
-else
-    echo "build of UML Linux kernel failed"
-    exit 1
-fi
+./uml/build_uml all || die "build of UML Linux kernel failed"
+create_rootfs
 
-exit 0
diff --git a/tools/cluster_sim_uml/uml/build_uml b/tools/cluster_sim_uml/uml/build_uml
--- a/tools/cluster_sim_uml/uml/build_uml
+++ b/tools/cluster_sim_uml/uml/build_uml
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /bin/sh
 #
 #      -*- OpenSAF  -*-
 #
@@ -17,18 +17,70 @@
 #
 #
 
+##
+## build_uml --
+##   Build script for the User Mode Linux (UML) for OpenSAF.
+##
+##   Files such as the Linux kernel archive will be downloaded
+##   automatically with "wget". The files will be stored in the
+##   directory defined by the $ARCHIVE variable.
+##
+## Syntax:
+##
+##   build_uml <sub-command> [options...]
+##
+## Environment:
+##
+##   All environment settings are optional.
+##
+##   $ARCHIVE - Should point to a directory where dowloaded files are
+##              stored.
+##   $CONFIGD - Contains configurations for different kernel and
+##              busybox versions (default ./config).
+##   $KVER -    The Linux kernel version to use.
+##   $BBVER -   The BusyBox version to use.
+##   $TIPCUTILSVER - The TIPC Util version to use.
+##
+## Sub-commands:
+##
+
+pgm=`basename $0`
+dir=`dirname $0`; dir=`cd $dir; pwd`
+tmp=/tmp/${pgm}$$
+
+die() {
+    echo "ERROR: $*" >&2
+    rm -rf $tmp
+    exit 1
+}
+help() {
+    grep '^##' $0 | cut -c3-
+    exit 0
+}
+test -n "$1" || help
+cd $dir
+archive=${ARCHIVE:-$dir/archive}
+configd=${CONFIGD:-$dir/config}
+
+kver=${KVER:-2.6.31}
+kurlbase=${KURLBASE:-"http://www.kernel.org/pub/linux/kernel/v2.6"}
+if echo $kver | grep -q -e '^2\.6\.[0-9]\+\.[0-9]\+$'; then
+    kbase=$(echo $kver | grep -o '2.6.[0-9]\+')
+    kurl="http://www.kernel.org/pub/linux/kernel/v2.6/linux-$kbase.tar.bz2"
+    purl="http://www.kernel.org/pub/linux/kernel/v2.6/patch-$kver.bz2"
+else
+    kurl="http://www.kernel.org/pub/linux/kernel/v2.6/linux-$kver.tar.bz2"
+fi
 tipcutilsver=${TIPCUTILSVER:-1.0.4}
 tipcutilsurl="http://prdownloads.sourceforge.net/tipc/tipcutils-$tipcutilsver.tar.gz"
-kver=${KVER:-2.6.24.3}
-kurl=${KURL:-"http://www.kernel.org/pub/linux/kernel/v2.6/linux-$kver.tar.bz2"}
-bbver=${BBVER:-1.9.1}
+
+bbver=${BBVER:-1.15.2}
 bburl="http://busybox.net/downloads/busybox-$bbver.tar.bz2"
 umlutilsver=20070815
 umlutilsurl="http://user-mode-linux.sourceforge.net/uml_utilities_$umlutilsver.tar.bz2"
+
 arch=$(uname -m)
 gid=$(id -g)
-
-test -x ./uml/build_uml || exit 1
 
 if [ $arch = x86_64 ]; then
     lib_dir=lib64
@@ -36,81 +88,168 @@ else
     lib_dir=lib
 fi
 
-get_and_extract()
-{
-    local file=archive/$1
-    local url=$2
-    local dir=$3
-
-    test -d $dir && return
-
-    if ! test -e $file; then
-        if ! wget -O $file $url; then
-            echo "Error, could not download $url"
-            rm -f $file
-            exit 1
-        fi
+##   info
+##     Printout general info.
+##
+cmd_info() {
+    echo "Base dir: $dir"
+    echo "Archive: $archive"
+    echo "Linux kernel $kver:"
+    f=$archive/$(basename $kurl)
+    test -r $f && exists="(exists)"
+    echo "    $f $exists"
+    echo "    $kurl"
+    if test -n "$purl"; then
+	f=$archive/$(basename $purl)
+	test -r $f && exists="(exists)"
+	echo "    $f $exists"
+	echo "    $purl"
     fi
+    echo "BusyBox $bbver:"
+    f=$archive/$(basename $bburl)
+    test -r $f && exists="(exists)"
+    echo "    $f $exists"
+    echo "    $bburl"
+    echo "TIPC Utils $tipcutilsver:"
+    f=$archive/$(basename $tipcutilsurl)
+    test -r $f && exists="(exists)"
+    echo "    $f $exists"
+    echo "    $tipcutilsurl"
+    echo "UML Utils $umlutilsver:"
+    f=$archive/$(basename $umlutilsurl)
+    test -r $f && exists="(exists)"
+    echo "    $f $exists"
+    echo "    $umlutilsurl"
+}
 
-    rm -rf $dir
+##   download
+##     Download all necessary packaget from the net using "wget". Make
+##     sure that your proxy-settings are correct.
+##
+cmd_download() {
+    mkdir -p $archive
+    for a in $kurl $purl $bburl $umlutilsurl $tipcutilsurl; do
+	f=$(basename $a)
+	if test -r $archive/$f; then
+	    echo "Already downloaded [$f]"
+	    continue
+	fi
+	wget -O $archive/$f $a || die "Download failed [$a]"
+    done
+}
 
-    if echo $file | grep bz2; then
-        tar xjf $file
-    else
-        tar xzf $file
+##   extract_kernel
+##     Unpack the Linux kernel.
+##     Prerequisite: Kernel and patch archives must have been downloaded.
+##
+cmd_extract_kernel() {
+    if test -d linux-$kver; then
+	echo "Already extracted [linux-$kver]"
+	return 0
     fi
-
-    if [ $? -ne 0 ]; then
-        echo "extraction of '$file' failed, consider delete it and start over"
-        exit 1
+    f=$archive/$(basename $kurl)
+    test -r $f || die "Not readable [$f]"
+    tar xjf $f
+    if ! test -d "linux-$kver"; then
+	mv linux-$kbase linux-$kver
+	f=$archive/$(basename $purl)
+	test -r $f || die "Not readable [$f]"
+	cd linux-$kver
+	bzcat $f | patch -p1 > /dev/null 2>&1
+	cd -
     fi
 }
 
-build_linux()
-{
-    if test -e bin/linux; then
-        return
-    fi
-
-    cp -L config/linux-config-$arch linux-$kver/.config
-    chmod +x linux-$kver/scripts/gen_initramfs_list.sh
-    ./linux-$kver/scripts/gen_initramfs_list.sh -u $UID -g $gid \
-        $top/root $top/root/dev/initramfs_list \
-        > linux-$kver/initramfs_list
-    make -C linux-$kver ARCH=um
+##   refresh_root
+##     Update the root/ directory, for instance when the root_template
+##     is altered.
+##
+cmd_refresh_root() {
+    rm -rf root
+    cmd_create_initramfs
 
     # Install modules into initramfs and rebuild Linux kernel
-    INSTALL_MOD_PATH=$top/root make -C linux-$kver arch=um modules_install
+    INSTALL_MOD_PATH=$dir/root make -C linux-$kver ARCH=um modules_install
     rm -f root/$lib_dir/modules/$kver/build \
         root/$lib_dir/modules/$kver/source \
         linux-$kver/initramfs_list
     ./linux-$kver/scripts/gen_initramfs_list.sh -u $UID -g $gid \
-        $top/root $top/root/dev/initramfs_list \
+        $dir/root $dir/root/dev/initramfs_list \
         > linux-$kver/initramfs_list
     rm -f linux-$kver/usr/initramfs_data.cpio.gz
-    make -C linux-$kver ARCH=um
-    cp linux-$kver/linux bin/linux
+    make -C linux-$kver -j4 ARCH=um
+
+    cp linux-$kver/vmlinux bin/linux
     strip bin/linux
 }
 
-build_busybox()
+cmd_patch_tipc_tolerance() {
+    tipc_cfg=$dir/linux-$kver/include/linux/tipc_config.h
+    grep -q 'TIPC_DEF_LINK_TOL 1500' $tipc_cfg || return 0
+    mv -f $tipc_cfg $tipc_cfg.orig
+    sed -e 's,TIPC_DEF_LINK_TOL 1500,TIPC_DEF_LINK_TOL 3500,' \
+	< $tipc_cfg.orig > $tipc_cfg
+    echo "Patched TIPC_DEF_LINK_TOL 3500"
+    return 0
+}
+
+##   build_linux
+##     Build the UML kernel.
+##
+cmd_build_linux()
+{
+    if test -x bin/linux; then
+	echo "Already built [bin/linux]"
+        return 0
+    fi
+    test -r $dir/root/dev/initramfs_list || die "Root-fs not built"
+
+    cfg=$configd/linux-$kver-$arch
+    test -r $cfg || cfg=config/linux-config-$arch
+    cp -L $cfg linux-$kver/.config
+    chmod +x linux-$kver/scripts/gen_initramfs_list.sh
+    ./linux-$kver/scripts/gen_initramfs_list.sh -u $UID -g $gid \
+        $dir/root $dir/root/dev/initramfs_list \
+        > linux-$kver/initramfs_list
+
+    cmd_patch_tipc_tolerance
+    make -C linux-$kver -j3 ARCH=um oldconfig
+    make -C linux-$kver -j4 ARCH=um
+    cmd_refresh_root
+}
+
+##   build_busybox
+##     Extract and buuild busybox.
+##
+cmd_build_busybox()
 {
     if test -e bin/busybox; then
+	echo "Already built [bin/busybox]"
         return
     fi
 
+    f=$archive/$(basename $bburl)
+    test -r $f || die "Not downloaded [$f]"
+    rm -rf busybox-$bbver
+    tar xjf $f
+
     mkdir -p bin
-    cp -L config/busybox-config busybox-$bbver/.config
+    cfg=$configd/busybox-$bbver
+    test -r $cfg || cfg=config/busybox-config
+    cp -L $cfg busybox-$bbver/.config
     make -C busybox-$bbver
     cp busybox-$bbver/busybox bin
 }
 
-# Build an incomplete ramfs; kernel modules are missing
-# Dependent on busybox
-create_initramfs()
+##   create_initramfs
+##     Build an incomplete ramfs; kernel modules are missing
+##     Dependent on busybox and tipc-utils.
+##
+cmd_create_initramfs()
 {
     if test -d root; then
-        return
+	echo "Already created [root/]"
+        return 0
     fi
 
     rm -rf root
@@ -121,15 +260,24 @@ create_initramfs()
         ln -fs /bin/busybox root/$n
     done
     cp -L `ldd ./bin/busybox | tr -s ' \t' '\n' | grep /$lib_dir | sed -e 's,/tls,,'` root/$lib_dir
-    cp -L /$lib_dir/libnss_files.so.? /$lib_dir/libpthread.so.? root/$lib_dir
+    cp -L /$lib_dir/libnss_files.so.? /$lib_dir/libpthread.so.? /$lib_dir/libm.so.? root/$lib_dir
     chown -hR $UID:$gid root
 }
 
-build_umlutils()
+##   build_umlutils
+##     Extract and build the UML tools.
+##
+cmd_build_umlutils()
 {
     if test -e bin/uml_mconsole; then
-        return
+	echo "Already built [bin/uml_mconsole]"
+        return 0
     fi
+
+    f=$archive/$(basename $umlutilsurl)
+    test -r $f || die "Not downloaded [$f]"
+    rm -rf tools-$umlutilsver
+    tar xjf $f
 
     make -C tools-$umlutilsver/lib
     make -C tools-$umlutilsver/uml_switch
@@ -142,27 +290,63 @@ build_umlutils()
     cp tools-${umlutilsver}/mconsole/uml_mconsole bin
 }
 
-build_tipcutils()
+##   build_tipcutils
+##     Extract and build tipcutils.
+##
+cmd_build_tipcutils()
 {
     if test -e bin/tipc-config; then
-        return
+	echo "Already built [bin/tipc-config]"
+        return 0
     fi
-    make KERNELDIR=$top/linux-$kver -C tipcutils-$tipcutilsver
+    f=$archive/$(basename $tipcutilsurl)
+    test -r $f || die "Not downloaded [$f]"
+    rm -rf tipcutils-$tipcutilsver
+    tar xzf $f
+
+    # Different build for older/newer kernels;
+    if ! make KERNELDIR=$dir/linux-$kver -C tipcutils-$tipcutilsver \
+	>/dev/null 2>&1; then
+	archd=$dir/linux-$kver/arch/x86
+	test "$(arch)" = "x86_64" && archd=$dir/linux-$kver/arch/ia64
+	make KERNELDIR="$dir/linux-$kver/include -I$archd" \
+	    -C tipcutils-$tipcutilsver || die "Build failed"
+    fi
     cp tipcutils-$tipcutilsver/tipc-config bin
 }
 
-cd uml
-mkdir -p archive
-top=$PWD
-get_and_extract tipcutils-$tipcutilsver.tar.gz $tipcutilsurl tipcutils-$tipcutilsver
-get_and_extract linux-$kver.tar.bz2 $kurl linux-$kver
-get_and_extract busybox-$bbver.tar.bz2 $bburl busybox-$bbver
-build_tipcutils
-build_busybox
-create_initramfs
-build_linux
-get_and_extract uml_utilities_${umlutilsver}.tar.bz2 $umlutilsurl tools-${umlutilsver}
-build_umlutils
-cd - > /dev/null
+##   clean
+##     Cleanup. Downloaded files are *not* removed.
+##
+cmd_clean() {
+    rm -rf linux-$kver busybox-$bbver root tipcutils-$tipcutilsver\
+        tools-$umlutilsver
+    for n in busybox tipc-config uml_mconsole uml_switch\
+        linux port-helper tunctl; do
+	rm -f bin/$n
+    done
+}
 
-exit 0
+##   all
+##     Dowload/extract/build everything.
+##     This corresponds to the old "./build_uml" without parameters.
+##
+cmd_all() {
+    cmd_download
+    cmd_build_tipcutils
+    cmd_build_busybox
+    cmd_create_initramfs
+    cmd_extract_kernel
+    cmd_build_linux
+    cmd_build_umlutils
+}
+
+cmd=$1; shift
+grep -q cmd_$cmd $dir/$pgm || die "Invalid command [$cmd]"
+trap "die Interrupted" INT TERM
+mkdir -p $tmp
+cmd_$cmd "$@"
+rc=$?
+rm -rf $tmp
+exit $rc
+
