Re-factor plmc_d to be a more traditional UNIX daemon
    Use getopt() instead of manual command line parsing
    Use daemon() instead of manual fork/exec
    Use flock to manage PID file
    Use a non-blocking socket to establish a connect() with a timeout
    Add a SIGTERM handler to send the UDP TERMINATING message
    Add -s and -x options so plmc_d can replace plmc_boot
    Remove plmc_boot binary and use plmcd as the replacement
    Rename plmc_d to plmcd
    Rename plmc_main init.d script to plmcd
    Document the plmcd.conf file
    Minor changes to simplify he plmcd.conf file

diff --git a/contrib/plmc/scripts/plmcd.in b/contrib/plmc/scripts/plmcd.in
--- a/contrib/plmc/scripts/plmcd.in
+++ b/contrib/plmc/scripts/plmcd.in
@@ -1,15 +1,15 @@
 #!/bin/sh
 #
 ### BEGIN INIT INFO
-# Provides: plmcboot
+# Provides: plmcd
 # Required-Start: $local_fs $remote_fs $network $syslog
-# Required-Stop: $local_fs $remote_fs  $network $syslog
+# Required-Stop: $local_fs $remote_fs $network $syslog
 # Should-Start: 
 # Should-Stop: 
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
-# Short-Description: send a UDP datagram to OpenSAF PLM controllers indicating OS state
-# Description: send a single UDP datagram to OpenSAF PLM controllers indications the OS state
+# Short-Description: starts/stops the plmcd daemon
+# Description: starts/stops the plmcd daemon
 ### END INIT INFO
 
 prog="plmcd"
@@ -19,32 +19,50 @@ configfile=/etc/plmcd.conf
 . /lib/lsb/init-functions
 
 if [ ! -r $configfile ]; then
-	logger -t $prog "can't read $configfile, exiting."
+	logger -t $prog "can't read /etc/plmcd.conf, exiting."
 	exit 6
 fi	
 
 binary=/usr/sbin/$prog
+lockfile=/var/lock/subsys/$prog
+pidfile=/var/run/$prog.pid
 
 RETVAL=0
 
 start() {
         [ -x $binary ] || exit 5
         echo -n "Starting $prog: "
-        start_daemon $binary -c $configfile -s
-        return $?
+        start_daemon $binary -c $configfile
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+		touch $lockfile
+		log_success_msg
+	else
+		log_failure_msg
+	fi
+        return $RETVAL
 }
 
 stop() {
         echo -n "Stopping $prog: "
-        start_daemon $binary -c $configfile -x
-        return $?
+	killproc -p $pidfile $prog
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+		rm -f $lockfile
+		log_success_msg
+	else
+		log_failure_msg
+	fi
+        return $RETVAL
 }
 
 restart() {
-        return 0
+        stop
+	start
 }
 
 tryrestart() {
+	[ -e $lockfile ] && restart
 	return 0
 }
 
@@ -56,6 +74,8 @@ reload() {
 }
 
 forcereload() {
+	reload
+	restart
 	return 0
 }
 
