plmc: cleanup whitespace crimes in the plmcd/plmcboot scripts

diff --git a/contrib/plmc/scripts/plmcboot.in b/contrib/plmc/scripts/plmcboot.in
--- a/contrib/plmc/scripts/plmcboot.in
+++ b/contrib/plmc/scripts/plmcboot.in
@@ -8,8 +8,8 @@
 # Should-Stop: 
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
-# Short-Description: send a UDP datagram to OpenSAF PLM controllers indicating OS state
-# Description: send a single UDP datagram to OpenSAF PLM controllers indications the OS state
+# Short-Description: Send a UDP datagram to OpenSAF PLM controllers indicating the OS state
+# Description: Send a UDP datagram to OpenSAF PLM controllers indicating the OS state
 ### END INIT INFO
 
 prog="plmcd"
@@ -31,67 +31,62 @@ fi
 RETVAL=0
 
 start() {
-        [ -x $binary ] || exit 5
-        echo -n "Starting $prog: "
-        if [ -f $lockfile ]
-        then
-              echo ""
-              return $RETVAL
-        fi
-        start_daemon $binary -c $configfile -s
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
-              touch $lockfile
-              log_success_msg
-        else
-              log_failure_msg
-        fi
-        return $RETVAL
-
+	[ -x $binary ] || exit 5
+	echo -n "Starting $prog: "
+	if [ -f $lockfile ]; then
+		echo ""
+		return $RETVAL
+	fi
+	start_daemon $binary -c $configfile -s
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
+		touch $lockfile
+		log_success_msg
+	else
+		log_failure_msg
+	fi
+	return $RETVAL
 }
 
 stop() {
-        echo -n "Stopping $prog: "
-        # If there is no lock file plmcboot was never run. Just return
-        if [ ! -f $lockfile ]
-        then
-                echo ""
-                return 1
-        fi
+	echo -n "Stopping $prog: "
+	# If there is no lock file plmcboot was never run. Just return
+	if [ ! -f $lockfile ]; then
+		echo ""
+		return 1
+	fi
 
-        # If plmcd is still running get out. Do not issue the message
-        ps -ef | grep $binary | grep -v grep >/tmp/plmcboot 2>&1
-        RETVAL=$?
-        while [ $RETVAL -eq 0 ]
-        do
-                sleep 1
-                ps -ef | grep $binary  | grep -v grep >/dev/null 2>&1
-                RETVAL=$?
-                let timeout=$timeout-1
-                if [ $timeout -le 0 ]
-                then
-                     break
-                fi
-        done
+	# If plmcd is still running get out. Do not issue the message
+	ps -ef | grep $binary | grep -v grep >/tmp/plmcboot 2>&1
+	RETVAL=$?
+	while [ $RETVAL -eq 0 ]; do
+		sleep 1
+		ps -ef | grep $binary  | grep -v grep >/dev/null 2>&1
+		RETVAL=$?
+		let timeout=$timeout-1
+		if [ $timeout -le 0 ]; then
+			break
+		fi
+	done
 
-        if [ $RETVAL -eq 0 ]; then
-                echo "Starting $prog failed as $binary is still running"
-                return 1
-        fi
-     
-        start_daemon $binary -c $configfile -x
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
+	if [ $RETVAL -eq 0 ]; then
+		echo "Starting $prog failed as $binary is still running"
+		return 1
+	fi
+
+	start_daemon $binary -c $configfile -x
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
 		rm -f $lockfile
 		log_success_msg
 	else
 		log_failure_msg
 	fi
-        return $RETVAL
+	return $RETVAL
 }
 
 restart() {
-        return 0
+	return 0
 }
 
 tryrestart() {
@@ -99,7 +94,7 @@ tryrestart() {
 }
 
 reload() {
-        echo -n "Reloading $prog: "
+	echo -n "Reloading $prog: "
 	log_warning_msg
 	logger -t $prog "reloading configuration is currently an unimplemented LSB feature"
 	return 3
@@ -125,7 +120,7 @@ case "$1" in
   restart)
 	restart
 	RETVAL=$?
-        ;;
+	;;
   try-restart|condrestart)
 	tryrestart
 	RETVAL=$?
@@ -133,15 +128,15 @@ case "$1" in
   reload)
 	reload
 	RETVAL=$?
-        ;;
+	;;
   force-reload)
 	forcereload
 	RETVAL=$?
-        ;;
+	;;
   status)
-        status
+	status
 	RETVAL=$?
-        ;;
+	;;
   *)
 	echo "Usage: $0 {start|stop|restart|try-restart|reload|force-reload|status}"
 	RETVAL=2
diff --git a/contrib/plmc/scripts/plmcd.in b/contrib/plmc/scripts/plmcd.in
--- a/contrib/plmc/scripts/plmcd.in
+++ b/contrib/plmc/scripts/plmcd.in
@@ -32,59 +32,55 @@ fi
 RETVAL=0
 
 start() {
-        [ -x $binary ] || exit 5
-        echo -n "Starting $prog: "
-        if [ ! -f $bootlockfile ]
-        then
-                RETVAL=1
-        fi
-        while [ $RETVAL -eq 1 ]
-        do
-                sleep 1
-                if [ ! -f $bootlockfile ]
-                then
-                      RETVAL=1
-                else
-                      RETVAL=0
-                fi
-                let timeout=$timeout-1
-                if [ $timeout -le 0 ]
-                then
-                     break
-                fi
-        done
+	[ -x $binary ] || exit 5
+	echo -n "Starting $prog: "
+	if [ ! -f $bootlockfile ]; then
+		RETVAL=1
+	fi
+	while [ $RETVAL -eq 1 ]; do
+		sleep 1
+		if [ ! -f $bootlockfile ]; then
+			RETVAL=1
+		else
+			RETVAL=0
+		fi
+		let timeout=$timeout-1
+		if [ $timeout -le 0 ]; then
+			break
+		fi
+	done
 
-        if [ $RETVAL -eq 1 ]; then
-                echo "Starting $prog failed. Run plmcboot start first"
-                return 1
-        fi
-     
-        start_daemon $binary -c $configfile
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
+	if [ $RETVAL -eq 1 ]; then
+		echo "Starting $prog failed. Run plmcboot start first"
+		return 1
+	fi
+
+	start_daemon $binary -c $configfile
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
 		touch $lockfile
 		log_success_msg
 	else
 		log_failure_msg
 	fi
-        return $RETVAL
+	return $RETVAL
 }
 
 stop() {
-        echo -n "Stopping $prog: "
+	echo -n "Stopping $prog: "
 	killproc -p $pidfile $prog
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
 		rm -f $lockfile
 		log_success_msg
 	else
 		log_failure_msg
 	fi
-        return $RETVAL
+	return $RETVAL
 }
 
 restart() {
-        stop
+	stop
 	start
 }
 
@@ -94,7 +90,7 @@ tryrestart() {
 }
 
 reload() {
-        echo -n "Reloading $prog: "
+	echo -n "Reloading $prog: "
 	log_warning_msg
 	logger -t $prog "reloading configuration is currently an unimplemented LSB feature"
 	return 3
@@ -107,26 +103,21 @@ forcereload() {
 }
 
 status() {
-        pid=`pidofproc -p ${pidfile} ${binary}`
-        ret=$?
-        if test "${ret}" = "0"
-        then
-                log_success_msg "$prog is running"
-                return $ret
-        elif test "${ret}" == "1"
-        then
-                log_warning_msg "$prog is dead and /var/run pid file exists"
-        elif test "${ret}" == "2"
-        then
-                log_warning_msg "$prog is dead and /var/lock lock file exists"
-        elif test "${ret}" == "3"
-        then
-                echo "$prog is not running"
-        elif test "${ret}" == "4"
-        then
-                log_warning_msg "$prog or service status is unknown"
-        fi
-        return $ret
+	pid=`pidofproc -p ${pidfile} ${binary}`
+	ret=$?
+	if [ $ret -eq 0 ]; then
+		log_success_msg "$prog is running"
+		return $ret
+	elif [ $ret -eq 1 ]; then
+		log_warning_msg "$prog is dead and /var/run pid file exists"
+	elif [ $ret -eq 2 ]; then
+		log_warning_msg "$prog is dead and /var/lock lock file exists"
+	elif [ $ret -eq 3 ]; then
+		echo "$prog is not running"
+	elif [ $ret -eq 4 ]; then
+		log_warning_msg "$prog or service status is unknown"
+	fi
+	return $ret
 }
 
 case "$1" in
@@ -141,7 +132,7 @@ case "$1" in
   restart)
 	restart
 	RETVAL=$?
-        ;;
+	;;
   try-restart|condrestart)
 	tryrestart
 	RETVAL=$?
@@ -149,15 +140,15 @@ case "$1" in
   reload)
 	reload
 	RETVAL=$?
-        ;;
+	;;
   force-reload)
 	forcereload
 	RETVAL=$?
-        ;;
+	;;
   status)
-        status
+	status
 	RETVAL=$?
-        ;;
+	;;
   *)
 	echo "Usage: $0 {start|stop|restart|try-restart|reload|force-reload|status}"
 	RETVAL=2
