Unify scripts for LOG, IMM & NTF
Ticket #461

- immd_script.in & immnd_script.in script almost identical.
- opensaf_lgs.in & opensaf_ntfs.in almost identical.
- BOM.xml comp args unified for LOG, IMM & NTF

diff --git a/scripts/opensaf_lgs.in b/scripts/opensaf_lgs.in
--- a/scripts/opensaf_lgs.in
+++ b/scripts/opensaf_lgs.in
@@ -20,31 +20,35 @@ echo "`date`: $0 $*"
 
 source "@sysconfdir@/@PACKAGE_NAME@/script.conf"
 
-BIN=${LIBPATH}/opensaf_saflogd
-LOGFILE=${NCS_STDOUTS_PATH}/opensaf_saflogd.log
-CONFIG=${SYSCONFDIR}/saflog.conf
-PIDFILE=${PIDPATH}/opensaf_saflogd.pid
+CMD=$1
 
-test -x $BIN || exit 1
-test -r $CONFIG || exit 1
-source $CONFIG
+NAME=opensaf_saflogd
+CONFFILE=${SYSCONFDIR}/saflog.conf
 
-mkdir -p $LOGSV_ROOT_DIRECTORY
+# Start generic part
+BIN=${LIBPATH}/${NAME}
+LOGFILE=${NCS_STDOUTS_PATH}/${NAME}.log
+PIDFILE=${PIDPATH}/${NAME}.pid
 
-case $1 in
+test -f $CONFFILE && source $CONFFILE
+test -f $PIDFILE && PID=`cat $PIDFILE`
+
+case "$CMD" in
     instantiate)
-        $LOGTOOL $BIN >> $LOGFILE 2>&1 &
+        if [ ! -x $BIN ]; then
+            logger -s -t $0 "ERROR: File $BIN does not exist or is not executable"
+            exit 1
+        fi
+        $TOOL $BIN >> $LOGFILE 2>&1 &
         ;;
     cleanup)
         if test -r $PIDFILE; then
-            PID=`cat $PIDFILE`
-
-            if [ "$LOGTOOL" == "" ]; then
+            if [ "$TOOL" == "" ]; then
                 kill -KILL $PID
             else
                 kill -TERM $PID
             fi
-            rm -f "$PIDFILE"
+            rm -f $PIDFILE
         fi
         ;;
     *)
diff --git a/scripts/opensaf_ntfs.in b/scripts/opensaf_ntfs.in
--- a/scripts/opensaf_ntfs.in
+++ b/scripts/opensaf_ntfs.in
@@ -15,39 +15,44 @@
 #
 # Author(s): Ericsson AB
 #
+
+echo "`date`: $0 $*"
+
 source "@sysconfdir@/@PACKAGE_NAME@/script.conf"
 
-command=opensaf_ntfd
-ntfsd=$LIBPATH/$command
-pidfile=$PIDPATH/$command.pid
-conf=${SYSCONFDIR}/ntf.conf
+CMD=$1
 
-test -r $conf || exit 1
-source $conf
+NAME=opensaf_ntfd
+CONFFILE=${SYSCONFDIR}/ntf.conf
 
-test -x $ntfsd || exit 1
+# Start generic part
+BIN=${LIBPATH}/${NAME}
+LOGFILE=${NCS_STDOUTS_PATH}/${NAME}.log
+PIDFILE=${PIDPATH}/${NAME}.pid
 
-case $1 in
-    start)
-        $NTFTOOL $ntfsd > "$NCS_STDOUTS_PATH/$command" 2>&1 &
+test -f $CONFFILE && source $CONFFILE
+test -f $PIDFILE && PID=`cat $PIDFILE`
+
+case "$CMD" in
+    instantiate)
+        if [ ! -x $BIN ]; then
+            logger -s -t $0 "ERROR: File $BIN does not exist or is not executable"
+            exit 1
+        fi
+        $TOOL $BIN >> $LOGFILE 2>&1 &
         ;;
-    clean)
-        if test -r $pidfile; then
-            PID=`cat $pidfile`
-            if [ "$NTFTOOL" == "" ]; then
+    cleanup)
+        if test -r $PIDFILE; then
+            if [ "$TOOL" == "" ]; then
                 kill -KILL $PID
             else
                 kill -TERM $PID
             fi
-            rm -f $pidfile
+            rm -f $PIDFILE
         fi
         ;;
-    dump)
-        # Dump internal data structures to console
-        kill -USR2 `cat $pidfile` 
-        ;;
     *)
-        echo "Usage: $0 {start|clean|dump}"
+        echo "Usage: $0 {instantiate|cleanup}"
         exit 1
 esac
 
