plm: add virtualization support - first version [#1431] PLMSv now supports management of virtualized EEs, and for this plmsv interfaces with libvirt. Normally, the path to libvirt headers and libraries will be found automatically by the configure script, using the pkg-config tool. If you need to build and link against custom libvirt headers and libraries that pkg-config does not know about, you may use the LIBVIRT_LIBS and LIBVIRT_CFLAGS variables, either exported in your environment or passed as options to the configure script.
PLM also supports virtualization of EEs using libvirt. To use virtualization
support in PLM, you will need to do the following:

1) Configure access to the hypervisor. This is done by adding an XML object of
   type OpenSafPlmVirtualMachineMonitorConfig. saPlmEE should point to the EE
   you have defined elsewhere for the hypervisor, and libVirtSession should
   be the URI libvirt should use to connect to the hypervisor. For KVM, this
   should be something like qemu+<transport>:doublebackslash<hostname>backslashsystem. Please see
   the libvirt documentation for your connection specifics.

        <object class=OpenSafPlmVirtualMachineMonitorConfig>
                <dn>plmVmmConfig=1,safApp=safPlmService</dn>
                <attr>
                        <name>saPlmEE</name>
                        <value>safEE=VirtualMachineMonitor,safHE=myHardwareHE,safDomain=mySafDomain</value>
                </attr>
                <attr>
                        <name>libVirtSession</name>
                        <value>qemu:///system</value>
                </attr>
        </object>

2) Map the virtual machine EE to the libvirt domain name. This is done by adding
   an XML object of type OpenSafPlmVirtualMachineConfig. saPlmEE should point
   to the EE you have defined elsewhere for the virtual machine, and
   libVirtDomainName should point to the libvirt name of the domain.

        <object class=OpenSafPlmVirtualMachineConfig>
                <dn>plmVmConfig=1,safApp=safPlmService</dn>
                <attr>
                        <name>saPlmEE</name>
                        <value>safEE=VirtualMachine1,safEE=VirtualMachineMonitor,safHE=myHardwareHE,safDomain=mySafDomain</value>
                </attr>
                <attr>
                        <name>libVirtDomainName</name>
                        <value>EE_test_1</value>
                </attr>
        </object>

3) libvirtd must be started in some fashion.

diff --git a/scripts/opensaf_reboot b/scripts/opensaf_reboot
--- a/scripts/opensaf_reboot
+++ b/scripts/opensaf_reboot
@@ -64,15 +64,20 @@ opensaf_reboot_with_plm()
 	immadm -o 7 $ee_name
 	retval=$?
 	if [ $retval != 0 ]; then
-		if [ "$self_node_id" = "$node_id" ];then
-			sudo /sbin/reboot -f
-		else
-			logger -t "opensaf_reboot" "Rebooting remote node failed"
-			exit 1
-		fi
-	fi 
+		logger -t "opensaf_reboot" "graceful restart failed for $ee_name: attempting abrupt restart"
+		immadm -o 7 -p restartOption:SA_STRING_T:abrupt $ee_name
+		retval=$?
+
+		if [ $retval != 0 ]; then
+			if [ "$self_node_id" = "$node_id" ];then
+				sudo /sbin/reboot -f
+			else
+				logger -t "opensaf_reboot" "abrupt restart failed for $ee_name: unable to restart remote node"
+				exit 1
+			fi
+		fi 
+	fi
 #Note: Operation Id SA_PLM_ADMIN_RESTART=7
-#No Parameter option specified, which signifies gracefull reboot
 #In the example the $ee_name would expand to (for eg:-) safEE=my_linux_os,safHE=64bitmulticore,safDomain=my_domain
 }
 
