dtm: allow initial sync for TCP only [#232]

diff --git a/osaf/services/infrastructure/dtms/scripts/osaf-transport-monitor.in b/osaf/services/infrastructure/dtms/scripts/osaf-transport-monitor.in
--- a/osaf/services/infrastructure/dtms/scripts/osaf-transport-monitor.in
+++ b/osaf/services/infrastructure/dtms/scripts/osaf-transport-monitor.in
@@ -29,30 +29,28 @@ fi
 
 if [ ! "$MDS_TRANSPORT" = "TIPC" ] ; then
 	prog="osafdtmd"
-fi
 
-RETVAL=0
-
-#Read the pid of dtmd.
-count=0
-while true
-do
-	if [ $count -eq 15 ] ; then
-		logger -s -t $prog "dtmd failed to come up. "
-		$pkglibdir/opensaf_reboot 0
-		exit 0;
-	fi
+	#Read the pid of dtmd.
+	count=0
+	while true
+	do
+		if [ $count -eq 15 ] ; then
+			logger -s -t $prog "dtmd failed to come up. "
+			$pkglibdir/opensaf_reboot 0
+			exit 0;
+		fi
 		
-	pidval=`cat $pkgpiddir/$prog.pid`
-	if  ! test -d /proc/$pidval ; then
-		#dtmd may not have been spawned yet, wait for it.
-		sleep 1
-		count=$(($count + 1))
-	else
-		#found the pid
-		break;
-	fi
-done
+		pidval=`cat $pkgpiddir/$prog.pid`
+		if  ! test -d /proc/$pidval ; then
+			#dtmd may not have been spawned yet, wait for it.
+			sleep 1
+			count=$(($count + 1))
+		else
+			#found the pid
+			break;
+		fi
+	done
+fi
 
 #start monitoring dtmd pid and rotate MDS logs
 echo "Running Permanent loop to clean MDS Logs..."
