dtms: remove bashisms only = is defined by posix (#665)

diff --git a/osaf/services/infrastructure/dtms/scripts/osaf-dtm.in b/osaf/services/infrastructure/dtms/scripts/osaf-dtm.in
--- a/osaf/services/infrastructure/dtms/scripts/osaf-dtm.in
+++ b/osaf/services/infrastructure/dtms/scripts/osaf-dtm.in
@@ -22,11 +22,11 @@ initscript=`basename $0`
 
 
 if [ ! -r $osafdirfile ]; then
-        logger -t $prog "can't read $osafdirfile, exiting."
-        exit 6
+	logger -t $prog "can't read $osafdirfile, exiting."
+	exit 6
 else
-        . $osafdirfile
-        . $pkgsysconfdir/dtmd.conf
+	. $osafdirfile
+	. $pkgsysconfdir/dtmd.conf
 fi
 
 binary=$pkglibdir/$prog
@@ -37,35 +37,35 @@ RETVAL=0
 
 start() {
 	export LD_LIBRARY_PATH=$pkglibdir:$LD_LIBRARY_PATH
-        [ -x $binary ] || exit 5
-        echo -n "Starting $prog: "
-        start_daemon -p $pidfile $binary  $args
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
+	[ -x $binary ] || exit 5
+	echo -n "Starting $prog: "
+	start_daemon -p $pidfile $binary  $args
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
 		touch $lockfile
 		log_success_msg
 		$pkgclcclidir/dh_monitoring & > /dev/null
 	else
 		log_failure_msg
 	fi
-        return $RETVAL
+	return $RETVAL
 }
 
 stop() {
-        echo -n "Stopping $prog: "
+	echo -n "Stopping $prog: "
 	killproc -p $pidfile $prog
-        RETVAL=$?
-        if [ $RETVAL -eq 0 ]; then
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
 		rm -f $lockfile
 		log_success_msg
 	else
 		log_failure_msg
 	fi
-        return $RETVAL
+	return $RETVAL
 }
 
 restart() {
-        stop
+	stop
 	start
 }
 
@@ -75,7 +75,7 @@ tryrestart() {
 }
 
 reload() {
-        echo -n "Reloading $prog: "
+	echo -n "Reloading $prog: "
 	log_warning_msg
 	logger -t $prog "reloading configuration is currently an unimplemented LSB feature"
 	return 3
@@ -88,26 +88,21 @@ forcereload() {
 }
 
 status() {
-        pid=`pidofproc -p ${pidfile} ${binary}`
-        ret=$?
-        if test "${ret}" = "0"
-        then
-                log_success_msg "$prog is running"
-                return $ret
-        elif test "${ret}" == "1"
-        then
-                log_warning_msg "$prog is dead and /var/run pid file exists"
-        elif test "${ret}" == "2"
-        then
-                log_warning_msg "$prog is dead and /var/lock lock file exists"
-        elif test "${ret}" == "3"
-        then
-                echo "$prog is not running"
-        elif test "${ret}" == "4"
-        then
-                log_warning_msg "$prog or service status is unknown"
-        fi
-        return $ret
+	pid=`pidofproc -p ${pidfile} ${binary}`
+	ret=$?
+	if [ $ret -eq 0 ]; then
+		log_success_msg "$prog is running"
+		return $ret
+	elif [ $ret -eq 1 ]; then
+		log_warning_msg "$prog is dead and /var/run pid file exists"
+	elif [ $ret -eq 2 ]; then
+		log_warning_msg "$prog is dead and /var/lock lock file exists"
+	elif [ $ret -eq 3 ]; then
+		echo "$prog is not running"
+	elif [ $ret -eq 4 ]; then
+		log_warning_msg "$prog or service status is unknown"
+	fi
+	return $ret
 }
 
 case "$1" in
@@ -122,7 +117,7 @@ case "$1" in
   restart)
 	restart
 	RETVAL=$?
-        ;;
+	;;
   try-restart|condrestart)
 	tryrestart
 	RETVAL=$?
@@ -130,15 +125,15 @@ case "$1" in
   reload)
 	reload
 	RETVAL=$?
-        ;;
+	;;
   force-reload)
 	forcereload
 	RETVAL=$?
-        ;;
+	;;
   status)
-        status
+	status
 	RETVAL=$?
-        ;;
+	;;
   *)
 	echo "Usage: $0 {start|stop|restart|try-restart|reload|force-reload|status}"
 	RETVAL=2
